#!/bin/bash
rm -fr /var/mobile/Library/Caches/com.apple.UIStatusBar
rm -fr /var/root/Library/Caches/com.apple.keyboards
rm -fr /var/mobile/Library/Caches/com.apple.keyboards
declare -a cydia 
cydia=($CYDIA) 
if [[ ${CYDIA+@} ]]; then 
eval "echo 'finish:restart' >&${cydia[0]}" 
fi
